// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftServe.ITAcademy.BackendDubbingProject.Utilities;

namespace SoftServe.ITAcademy.BackendDubbingProject.Migrations
{
    [DbContext(typeof(DubbingContext))]
    partial class DubbingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("SoftServe.ITAcademy.BackendDubbingProject.Models.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileName");

                    b.Property<int>("LanguageId");

                    b.Property<int>("SpeechId");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("SpeechId");

                    b.ToTable("Audios");
                });

            modelBuilder.Entity("SoftServe.ITAcademy.BackendDubbingProject.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("SoftServe.ITAcademy.BackendDubbingProject.Models.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("SoftServe.ITAcademy.BackendDubbingProject.Models.Speech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PerformanceId");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PerformanceId");

                    b.ToTable("Speeches");
                });

            modelBuilder.Entity("SoftServe.ITAcademy.BackendDubbingProject.Models.Audio", b =>
                {
                    b.HasOne("SoftServe.ITAcademy.BackendDubbingProject.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoftServe.ITAcademy.BackendDubbingProject.Models.Speech", "Speech")
                        .WithMany("Audios")
                        .HasForeignKey("SpeechId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SoftServe.ITAcademy.BackendDubbingProject.Models.Speech", b =>
                {
                    b.HasOne("SoftServe.ITAcademy.BackendDubbingProject.Models.Performance", "Performance")
                        .WithMany("Speeches")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
